### ISSUE TITLE
Check that linesegdist.py is correct

### ISSUE THREAD

**Issue by LarsAstrom** [LarsAstrom/Notebook#19]
Some methods have proved to be wrong. And the methods are not very consistent. Fix this.

- [ ] LineLine
- [ ] LineSeg
- [ ] LinePoint
- [ ] SegSeg
- [ ] SegPoint
- [ ] dist
- [ ] twopointstoline

**Comment by exoji2e** [comment]
LineLine should be implemented like [this](https://github.com/exoji2e/notebook/blob/master/code/Geometry/geometry.py#L27)
