### ISSUE TITLE
Move around stuff

### ISSUE THREAD

**Issue by exoji2e** [LarsAstrom/Notebook#3]
Tänkte flytta all er kod till en folder `code/`
Och lägga in en latex-fil som importerar koden och l'gger ut den snyggt, samt ett make-script, så att ni kan bygga er notebook med commandot `make`, givet att ni har `latex` installerat.

Jag kan fixa detta, om ni ger mig tumme upp :P

**Comment by BjornMagn** [comment]
Tumme upp
